on: push

jobs:
  experiment:
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ runner.os }}

