on: push

jobs:
  experiment:
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: ccache
        uses: amtep/ccache-action@18ce5be3e986db584ee491e0dcf271e4c40b44fc
        with:
          key: ${{ runner.os }}

